### PR TITLE
[Deprecation] Rails 6.1 Upgrade warning - update_attributes is deprecated

### PR DESCRIPTION
**Pull request by ghu-ut**
Resolves this `rails-server` deprecation warning: https://github.com/user-interviews/rails-server/issues/17057

`update_attributes` will be deprecated in Rails 6.1, change to `update`.

### CODE REVIEW

**Review by jeffbax — COMMENTED** [review]
is there a deprecation list item we can remove along side this? generally we're trying to have the changeset atomically cover one of the exception rule lines we've carved out

**Comment by ghu-ut** [comment]
> is there a deprecation list item we can remove along side this? generally we're trying to have the changeset atomically cover one of the exception rule lines we've carved out

@jeffbax Yes, this covers the deprecation described in this issue: https://github.com/user-interviews/rails-server/issues/17057

The trace from the warning then running `spec/models/response_set_spec.rb` in `rails-server` points to this issue in surveyor.  

I was thinking that order matters here since we're working across repos, so I wanted to make the change in surveyor first and then follow with the update to our deprecation.yml list in rs afterwards.

**Review by bsaris-ut — APPROVED** [review]
Oh God I forgot we have to update surveyor.... One day I'll just get rid of this gem and have a dance party.

Thanks for taking care of this.

**Comment by jeffbax** [comment]
ahhhh, totally missed this was surveyor repo and not rails server

**Comment by bsaris-ut** [comment]
@gretahayes19 just making sure that we have an eye on adding a new tag and updating the gemfile in the rails-server repo to make sure we get this change there.

**Comment by ghu-ut** [comment]
> @gretahayes19 just making sure that we have an eye on adding a new tag and updating the gemfile in the rails-server repo to make sure we get this change there.

Yes, thanks for this reminder! Done [here](https://github.com/user-interviews/rails-server/pull/17071).

**Pull request merged**
